### ISSUE TITLE
Need help on MIDI commands

### ISSUE THREAD

**Issue by JuanGonnet** [CodeKill3r/BCD2000HIDplus#4]
Hi, i'm from Argentina (sorry for my bad english).
First, i send my congratulations to the people working in this project, is very usefull.
I just update the firmware with the 'tusboot.bin' file downloaded from here.
When i connect'd in Windows PC to test it, and verified in Device Manager, i see 2 new devices (the midi and the soundcard). Looks good!
Well, in DJ software (Virtual DJ) i have noticed to the new device, and ican to set up the sound with no issues, but the MIDI commands in the mapper is empty and i need to fill one by one manually.
I want to know is there a mapper for VirtualDJ or Mixxx successfully working? 
Thanks in advance.

**Comment by xd2** [comment]
Hi @JuanGonnet.

Mixxx mapping from @davy39 here : https://github.com/davy39/mixxx-bcd2000

LEDs are not lightning with Mixx on my side unfortunately as mentioned [on my issue](https://github.com/davy39/mixxx-bcd2000/issues/1).

**Comment by CodeKill3r** [comment]
Creating and using mappings are not the scope of this project, sorry.
